Repository sendgrid/ruby-http-client, pull requests merged in 2018-10, with the labels that each got.

#76 Add Gemfile
  .gitignore
  Gemfile
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#66 delete PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#73 Create a Use Cases Directory
  use_cases/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#75 Add ability to set proxy
  examples/example.rb
  lib/ruby_http_client.rb
  test/test_ruby_http_client.rb
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#72 Add USAGE.md
  USAGE.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#80 Missing Dev Dependencies + rubocop #79
  .rubocop.yml
  Rakefile
  lib/ruby_http_client.rb
  ruby_http_client.gemspec
  test/test_helper.rb
  test/test_ruby_http_client.rb
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#91 update contribution to branch off development
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#86 Add first time contributor documentation
  first-timers.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#61 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: ready for deploy, type: docs update
