Repository sendgrid/ruby-http-client, pull requests merged in 2020-02, with the labels that each got.

#95 Fix JSON body reencoding and Rubocop configuration
  .rubocop.yml
  lib/ruby_http_client.rb
  test/test_ruby_http_client.rb
Labels: difficulty: medium, status: code review request, status: hacktoberfest approved

#115 fix: update incorrect gem name
  .travis.yml
Labels: difficulty: easy, status: code review request, type: bug

#92 Add CodeCov support to .travis.yml
  .travis.yml
  ruby_http_client.gemspec
  test/test_helper.rb
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved, type: sendgrid enhancement

#84 docs: Corrected *.md files using Grammarly
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#67 fix: Split up the build_request function to logical component functions to reduce method complexity
  lib/ruby_http_client.rb
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#98 test: Fix rubocop.yml formatting warnings
  .rubocop.yml
Labels: difficulty: medium, status: code review request, status: hacktoberfest approved

#68 feat: add ratelimit support
  examples/example.rb
  lib/ruby_http_client.rb
  test/test_ruby_http_client.rb
Labels: difficulty: medium, status: code review request, type: sendgrid enhancement

#116 chore: add Ruby 2.7 to Travis
  .travis.yml
  README.md
Labels: status: code review request

#118 fix: JSON-encode array request bodies
  lib/ruby_http_client.rb
  test/test_ruby_http_client.rb
Labels: status: code review request
